# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ouWdD_hfb8hSlpNdJSdN2vI-KHk5Uwye
"""

############# CONFIGURACIÓN INICIAL ##############
##################################################

# Commented out IPython magic to ensure Python compatibility.
import numpy as np          # importamos numpy como np
import pandas as pd         # importamos pandas como pd
import math
import random
import warnings
# Ignorar advertencias de convergencia para los modelos lineales
warnings.filterwarnings('ignore', category=UserWarning, module='sklearn')

# Cargamos módulos de análisis gráficos
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
sns.set_theme(style = 'whitegrid')
# %config InlineBackend.figure_format = 'retina'

#===============================================
# Cargar funciones variables aleatorias
from urllib.request import urlretrieve
import re # for text manipulation

url = 'https://raw.githubusercontent.com/asunmayoral/umh1477/refs/heads/main/bloque1_sps.py'
urlretrieve(url, 'bloque1_sps.py')
import bloque1_sps
from bloque1_sps import *

#========================================================================
###################### Funciones para CMTC ##############################
#========================================================================

# Función para la rerpesentación gráfica de la función de probabildiad y de distribución de una variable aleatoria discreta
def graficar_discreta(x, fx):
  """
  Función para representar gráficamente la función de masa de probabilidad y la función de distribución de una variable discreta.

  Args:
    x: valores de la variable discreta
    fx: función de masa de probabilidad para cada valor de x

  Returns:
    Gráficos de la función de masa de probabilidad y la función de distribución.
  """
  # posiciones en el gráfico de los valores d ela variable discreta
  pos = np.arange(len(x))
  # Función de distribución
  fdist = [sum(fx[:(l+1)]) for l in range(len(fx))]

  # Entorno gráfico
  fig, ax = plt.subplots(1, 2, figsize=(7, 4))
  # Pintamos los puntos con x y la función de masa de probabilidad
  ax[0].plot(pos, fx, 'bo');
  # Dibujamos las líneas verticales correspondientes con sus caractarísticas
  ax[0].vlines(pos, 0, fx, colors='b', lw=5, alpha=0.5);
  # Ponemos un título
  ax[0].set_title('Función de masa de probabilidad')
  # Ponemos etiquetas a los ejes x e y
  ax[0].set_xticks(pos, labels=x)
  ax[0].set_ylabel('Probabilidad')
  ax[0].set_xlabel('Espacio muestral')

  #### Función de distribución
  # Pintamos los puntos con x y la función de distribución
  ax[1].plot(pos, fdist, 'bo');
  # Dibujamos las líneas verticales correspondientes con sus caractarísticas
  ax[1].vlines(pos, 0, fdist, colors='b', lw=5, alpha=0.5);
  # Ponemos un título
  ax[1].set_title('Función de distribución')
  # Ponemos etiquetas a los ejes x e y
  ax[1].set_xticks(pos, labels=x)
  ax[1].set_ylabel('Probabilidad')
  ax[1].set_xlabel('Espacio muestral')
  plt.tight_layout()

# Función para obtener un dataframe con la función de masa de probabilidad y la función de distribución de una variable discreta.
def distr_discreta(x, fx):
  """
  Función para obtener un dataframe con la función de masa de probabilidad y la función de distribución de una variable discreta.

  Args:
    x: valores de la varaible discreta
    fx: función de masa de probabilidad

  Returns:
    pdDataFrame con los valores de la variable, la función de masa de probabilidad y la función de distribución.
  """
  # posiciones en el gráfico de los valores d ela variable discreta
  pos = np.arange(len(x))
  # Función de distribución
  fdist = [sum(fx[:(l+1)]) for l in range(len(fx))]
  return(pd.DataFrame({"x": x, "fmp":fx, "fdist":fdist}))

### Funciones para procesos de Poisson
######################################

def generate_poisson_events(rate, time_duration):
  """
  La función generate_poisson_events simula un proceso de Poisson mediante la generación de eventos
  con una tasa promedio dada (rate) durante un período de tiempo especificado (time_duration).

  La función devuelve el número de eventos (num_events), los tiempos de los eventos (event_times) y
  los tiempos entre llegadas correspondientes (inter_arrival_times), lo que proporciona una
  representación de un proceso de Poisson.
  """
  num_events = np.random.poisson(rate * time_duration)
  event_times = np.sort(np.random.uniform(0, time_duration, num_events))
  inter_arrival_times = np.diff(event_times)
  return num_events, event_times, inter_arrival_times


def plot_non_sequential_poisson(num_events, event_times, inter_arrival_times, rate, time_duration):
  """
  La función plot_non_sequential_poisson crea una visualización de dos paneles de
  una simulación de proceso de Poisson no secuencial. El primer panel muestra los tiempos de los eventos
  y el segundo muestra un histograma de los tiempos entre llegadas entre eventos.

  La función acepta la cantidad de eventos (num_events), los tiempos de los eventos (event_times),
  los tiempos entre llegadas (inter_arrival_times), la tasa (rate) del proceso de Poisson y
  la duración total de la simulación como entrada (time_duration).
  """
  fig, axs = plt.subplots(1, 2, figsize=(15, 6))
  fig.suptitle(f'Poisson Process Simulation (λ = {rate}, Duration = {time_duration} seconds)\n', fontsize=16)

  axs[0].step(event_times, np.arange(1, num_events + 1), where='post', color='blue')
  axs[0].set_xlabel('Time')
  axs[0].set_ylabel('Event Number')
  axs[0].set_title(f'Poisson Process Event Times\nTotal: {num_events} events\n')
  axs[0].grid(True)

  axs[1].hist(inter_arrival_times, bins=20, color='green', alpha=0.5)
  axs[1].set_xlabel('Inter-Arrival Time')
  axs[1].set_ylabel('Frequency')
  axs[1].set_title(f'Histogram of Inter-Arrival Times\nMEAN: {np.mean(inter_arrival_times):.2f} | STD: {np.std(inter_arrival_times):.2f}\n')
  axs[1].grid(True, alpha=0.5)

  plt.tight_layout()
  plt.show()


def plot_sequential_poisson(num_events_list, event_times_list, inter_arrival_times_list, rate, time_duration):
  """
  La función plot_sequential_poisson es responsable de generar un gráfico secuencial de eventos de procesos de Poisson
  simulados con diferentes tasas de llegada. Crea una figura de subgráfico de 2x1 que muestra los tiempos de los eventos
  y un histograma de los tiempos entre llegadas. Cada subgráfico muestra datos para múltiples procesos de Poisson
  con diferentes tasas, que se distinguen por colores distintos. La función toma num_events_list, event_times_list
  e inter_arrival_times_list como entrada, que contienen estadísticas de eventos para cada tasa, junto con la lista de
  tasas que especifica los valores lambda y time_duration que indica la duración de la simulación.

  Visualiza los datos, mostrando la ocurrencia de eventos a lo largo del tiempo y la distribución de los tiempos
  entre llegadas, lo que ayuda a comparar y analizar procesos de Poisson con diferentes tasas de llegada en un solo gráfico.
  """
  fig, axs = plt.subplots(1, 2, figsize=(15, 6))
  fig.suptitle(f'Poisson Process Simulation (Duration = {time_duration} seconds)\n', fontsize=16)

  axs[0].set_xlabel('Time')
  axs[0].set_ylabel('Event Number')
  axs[0].set_title(f'Poisson Process Event Times')
  axs[0].grid(True)

  axs[1].set_xlabel('Inter-Arrival Time')
  axs[1].set_ylabel('Frequency')
  axs[1].set_title(f'Histogram of Inter-Arrival Times')
  axs[1].grid(True, alpha=0.5)

  color_palette = plt.get_cmap('tab20')
  colors = [color_palette(i) for i in range(len(rate))]

  for n, individual_rate in enumerate(rate):
      num_events = num_events_list[n]
      event_times = event_times_list[n]
      inter_arrival_times = inter_arrival_times_list[n]

      axs[0].step(event_times, np.arange(1, num_events + 1), where='post', color=colors[n], label=f'λ = {individual_rate}, Total Events: {num_events}')
      axs[1].hist(inter_arrival_times, bins=20, color=colors[n], alpha=0.5, label=f'λ = {individual_rate}, MEAN: {np.mean(inter_arrival_times):.2f}, STD: {np.std(inter_arrival_times):.2f}')

  axs[0].legend()
  axs[1].legend()

  plt.tight_layout()
  plt.show()


def poisson_simulation(rate, time_duration, show_visualization=True):
    """
    La función poisson_simulation simula un proceso de Poisson con una sola tasa o una lista de tasas
    durante un período de tiempo especificado. Si se proporciona una sola tasa, genera eventos de Poisson
    y sus tiempos entre llegadas y, opcionalmente, los visualiza. Si se proporciona una lista de tasas,
    genera eventos de Poisson y tiempos entre llegadas para cada tasa y, opcionalmente, los visualiza
    de forma secuencial (show_visualization = True).

    La función devuelve las estadísticas de eventos número de eventos (num_events_list), tiempos de
    eventos (event_times_list), tiempos entre llegadas (inter_arrival_times_list) cuando la visualización
    está desactivada o None cuando la visualización está habilitada.
    """
       
    if isinstance(rate, int):
        num_events, event_times, inter_arrival_times = generate_poisson_events(rate, time_duration)

        if show_visualization:
            plot_non_sequential_poisson(num_events, event_times, inter_arrival_times, rate, time_duration)
        else:
            return num_events, event_times, inter_arrival_times

    elif isinstance(rate, list):
        num_events_list = []
        event_times_list = []
        inter_arrival_times_list = []

        for individual_rate in rate:
            num_events, event_times, inter_arrival_times = generate_poisson_events(individual_rate, time_duration)
            num_events_list.append(num_events)
            event_times_list.append(event_times)
            inter_arrival_times_list.append(inter_arrival_times)

        if show_visualization:
            plot_sequential_poisson(num_events_list, event_times_list, inter_arrival_times_list, rate, time_duration)
        else:
            return num_events_list, event_times_list, inter_arrival_times_list

## Función para obtener la matriz de tasas y la matriz generadora de una CMTC
#############################################################################
def matriz_tasas_generadora(tiempos, prob):
  """
  Función para obtener la matriz de tasas (R) y la matriz generadora (Q) a
  partir de los tiempos de permanenecia y las probabildiades de salto del proceso.

  Valores de entrada:
  - tiempos: lista con tiempos de permanencia de cada estado
  - prob: matriz de probabilidades de salto

  Valores de salida:
  - R: matriz de tasas
  - Q: matriz generadora
  """
  # Convertimos en arrays las lsitas de entrada
  tiempos = np.array(tiempos)
  prob = np.array(prob)
  # Tasas de permanencia
  tasas_permanencia = np.zeros(len(tiempos))
  # Calcula tasas de permanencia solo para tiempos distintos de cero
  mask = tiempos != 0
  tasas_permanencia[mask] = 1 / tiempos[mask]
  # Matriz de tasas
  R = np.round(tasas_permanencia[:, np.newaxis] * prob,2)
  # Matriz generadora
  Q = np.round(R - np.diag(tasas_permanencia),2)
  return R,Q

## Clase para el análisis de CMTC
#############################################################################
# Métodos contenidos
#  * matriz_prob_salto: Obtiene la matriz de probabildiad de salto dividiendo cada elemento de cada fila de tasas por la suma de la fila.
#  * matriz_prob_trans: Calcula la matriz de probabilidades de transición en el instante ts.
#  * tiempos_ocupacion: Calcula los tiempos de ocupación hasta el instante Ts.
#  * distr_lim_general:  Calcula la distribución límite
#  * tiempos_primer_paso: Calcula los tiempos de primer paso al conjunto de estados A.
#  *  

class CMTC:
    def __init__(self, Rmat): # Add estados as an argument
        """
        Inicializa la clase CMTC con la matriz de tasas Rmat y los estados.
        """
        self.Rmat = np.array(Rmat)

    def matriz_prob_salto(self, estados):
        """Obtiene la matriz de probabildiad de salto dividiendo cada elemento de cada fila de tasas por la suma de la fila."""
        Rmat = self.Rmat
        suma_filas = np.sum(Rmat, axis=1, keepdims=True)
        # Evitar la división por cero
        suma_filas[suma_filas == 0] = 1
        tasas_normalizadas = Rmat / suma_filas
        return pd.DataFrame(np.round(tasas_normalizadas, 6),index=estados, columns=estados)

    def matriz_prob_trans(self, estados, ts, cal=1):
        """
        Calcula la matriz de probabilidades de transición en el instante ts.
        """
        epsilon=1e-05
        Rmat = self.Rmat
        ris = np.sum(Rmat, axis=1)
        rlimit = np.max(ris) if cal == 1 else np.sum(Rmat)
        hatP = Rmat / rlimit
        np.fill_diagonal(hatP, 1 - ris / rlimit)
        rts = rlimit * ts
        A = hatP
        c = np.exp(-rts)
        B = c * np.identity(Rmat.shape[0])
        suma = c
        k = 1
        while suma < (1 - epsilon):
            c = c * rts / k
            B = B + c * A
            A = A @ hatP
            suma = suma + c
            k = k + 1
        B = pd.DataFrame(np.round(B, 6), index=estados, columns=estados)
        return B

    def tiempos_ocupacion(self, estados, Ts, cal=1):
        """
        Calcula los tiempos de ocupación hasta el instante Ts.
        """
        epsilon = 1e-05
        Rmat = self.Rmat
        ris = np.sum(Rmat, axis=1)
        rlimit = np.max(ris) if cal == 1 else np.sum(Rmat)
        hatP = Rmat / rlimit
        np.fill_diagonal(hatP, 1 - ris / rlimit)
        k = 0
        A = hatP.copy()
        yek = math.exp(-rlimit * Ts)
        ygk = 1 - yek
        suma = ygk
        B = ygk * np.identity(Rmat.shape[0])
        cota = Ts - epsilon
        while suma / rlimit < cota:
            k += 1
            yek = yek * (rlimit * Ts) / k
            ygk = ygk - yek
            B = B + ygk * A
            A = A @ hatP
            suma = suma + ygk
        resultados = pd.DataFrame(np.round(B / rlimit, 6), index=estados, columns=estados)
        return resultados

    def distr_lim_general(self, estados):
        """
        Calcula la distribución límite.
        """
        Rmat = self.Rmat
        N = Rmat.shape[0]
        sumarows = np.diag(np.sum(Rmat, axis=1))
        A = Rmat.T - sumarows
        A[N - 1, :] = np.ones(N)
        b = np.zeros(N)
        b[N - 1] = 1
        p = np.linalg.solve(A, b)
        p = pd.DataFrame(np.round(p, 6), index=estados, columns=['p'])
        return p

    def tiempos_primer_paso(self, A, estados):
        """
        Calcula los tiempos de primer paso al conjunto de estados A.
        """
        Rmat = self.Rmat
        estados = [str(estado) for estado in estados]
        rts = np.diag(np.sum(Rmat, axis=1))
        Rmod = Rmat[~np.isin(np.arange(Rmat.shape[0]), A), :]
        Rmod = Rmod[:, ~np.isin(np.arange(Rmat.shape[1]), A)]
        rates = rts[~np.isin(np.arange(rts.shape[0]), A), :]
        rates = rates[:, ~np.isin(np.arange(rts.shape[1]), A)]
        lms = Rmod.shape[0]
        B = rates - Rmod
        CS = np.ones(lms)
        ps = np.linalg.solve(B, CS)
        resultados = {}
        for i, estado in enumerate(estados):
            if i not in A:
                resultados[f"estado {estado}"] = ps[i]
        return resultados

###################################
### Simulación de sistemas
###################################

############# Sistema Ejemplo 1. Estación ITV

def simular_ITV(tasa_llegadas, tasa_servicio, servidores, tiempo):
  """
  Función para simular el sistema ITV del ejemplo 1

  Parámetros de entrada:
  - tasa_llegadas: Tasa de llegadas de clientes (clientes/minuto) al sistema
  - tasa_servicio: Tasa de servicio de clientes en cada estación (clientes/minuto)
  - servidores: Número de servidores en cada estación
  - tiempo: Tiempo de simulación (minutos)

  Devuelve: 
  - Datframe con las columnas:
    - 'S1_Tin': instante de tiempo de entrada a la estación 1 
    - 'S1_Tinit_service': instante de tiempo de inicio de servicio en la estación 1 
    - 'S1_Tout': instante de tiempo de salida en la estación 1 
    - 'S1_Tsystem': tiempo de permanencia en la estación 1
    - 'S1_Tqueue': tiempo de permanencia en la cola de la estación 1
    - 'S1_Nsystem': número de clientes en el sistema en la estación 1 cuando accede el nuevo cliente
    - 'S1_Nqueue': número de clientes en la cola de la estación 1 cuando accede el nuevo cliente
    - 'S2_Tin': instante de tiempo de entrada a la estación 2 
    - 'S2_Tinit_service': instante de tiempo de inicio de servicio en la estación 2 
    - 'S2_Tout': instante de tiempo de salida en la estación 2 
    - 'S2_Tsystem': tiempo de permanencia en la estación 2
    - 'S2_Tqueue': tiempo de permanencia en la cola de la estación 2
    - 'S2_Nsystem': número de clientes en el sistema en la estación 2 cuando accede el nuevo cliente
    - 'S2_Nqueue': número de clientes en la cola de la estación 2 cuando accede el nuevo cliente    
    - 'S3_Tin': instante de tiempo de entrada a la estación 3 
    - 'S3_Tinit_service': instante de tiempo de inicio de servicio en la estación 3 
    - 'S3_Tout': instante de tiempo de salida en la estación 3 
    - 'S3_Tsystem': tiempo de permanencia en la estación 3
    - 'S3_Tqueue': tiempo de permanencia en la cola de la estación 3
    - 'S3_Nsystem': número de clientes en el sistema en la estación 3 cuando accede el nuevo cliente
    - 'S3_Nqueue': número de clientes en la cola de la estación 3 cuando accede el nuevo cliente 
  """
  import simpy

  # Define the simulation environment
  env = simpy.Environment()
  results =[]  
  # Definimos los recursos de cada estación
  servers1 = servidores[0]; servers2 = servidores[1]; servers3 = servidores[2]
  station1 = simpy.Resource(env, capacity = servers1)
  station2 = simpy.Resource(env, capacity = servers2)
  station3 = simpy.Resource(env, capacity = servers3)

  #### B1. Inicialización de tiempos del sistema  #####
  #####################################################

  # Clase para la incialización de tiempos en el sistema de cada llegada
  class Sistema:
    def __init__(self, id):
        self.id = id
        self.station1_tarr = 0
        self.station1_tini = 0
        self.station1_tout = 0
        self.station2_tarr = 0
        self.station2_tini = 0
        self.station2_tout = 0
        self.station3_tarr = 0
        self.station3_tini = 0
        self.station3_tout = 0

  #### B2. Funcionamiento por el sitema  #####
  ############################################

  # Función para simular los datos de una estación
  def simular_estacion(env, material, station, tasa_servicio, station_name):
    # Tiempo de llegada a la estación
    setattr(material, f"{station_name}_tarr", env.now)
    with station.request() as req:
        # Número de clientes en el sistema y en la cola
        nsystem = len(station.queue) + station.count
        nqueue = len(station.queue)
        yield req
        # Tiempo de inicio del servicio
        setattr(material, f"{station_name}_tini", env.now)
        # Tiempo de servicio
        yield env.timeout(random.expovariate(tasa_servicio))
    # Tiempo de salida de la estación
    setattr(material, f"{station_name}_tout", env.now)
    # Guardar datos de la estación
    return [material.id,
            getattr(material, f"{station_name}_tarr"),
            getattr(material, f"{station_name}_tini"),
            getattr(material, f"{station_name}_tout"),
            getattr(material, f"{station_name}_tout") - getattr(material, f"{station_name}_tarr"),
            getattr(material, f"{station_name}_tini") - getattr(material, f"{station_name}_tarr"),
            nsystem, nqueue]

  ## Movimiento por el sistema
  def servicio(env, material):
    # Estación 1
    station1_data = yield env.process(simular_estacion(env, material, station1, tasa_servicio[0], "station1")) # Get station1 data
    # Estación 2
    station2_data = yield env.process(simular_estacion(env, material, station2, tasa_servicio[1], "station2")) # Get station2 data
    # Estacion 3
    station3_data = yield env.process(simular_estacion(env, material, station3, tasa_servicio[2], "station3")) # Get station3 data

    # unimos los resultados de las estaciones
    results.append(station1_data + station2_data + station3_data)

  #### B3. proceso de llegadas al sistema  #####
  ##############################################

  # Definimos el proceso de llegadas
  def llegadas(env, simulation_time):
    material_id = 1
    while env.now < simulation_time:  # Admit materials until simulation time
        yield env.timeout(random.expovariate(tasa_llegadas))  # arrivals per minute
        material = Sistema(material_id)
        env.process(servicio(env, material))
        material_id += 1

  ### Simulación y almacenamiento de resultados ###
  #################################################

  # Ejecutamos la simulación
  simulation_time = tiempo  # Define simulation time
  env.process(llegadas(env, simulation_time))  # Pass simulation time to material_arrival
  env.run(until=simulation_time)  # Simulate for the defined time

  # Dataframe de resultados
  df = pd.DataFrame(results, columns=['Material ID',
                                    'S1_Tin', 'S1_Tinit_service', 'S1_Tout', 'S1_Tsystem', 'S1_Tqueue', 'S1_Nsystem', 'S1_Nqueue',
                                    'Material ID', 'S2_Tin', 'S2_Tinit_service', 'S2_Tout', 'S2_Tsystem', 'S2_Tqueue', 'S2_Nsystem', 'S2_Nqueue',
                                    'Material ID', 'S3_Tin', 'S3_Tinit_service', 'S3_Tout', 'S3_Tsystem', 'S3_Tqueue', 'S3_Nsystem', 'S3_Nqueue'])
  df = df.sort_values(by=['S1_Tin'])

  # Tiempos totales en el sistema y en al cola
  df['System_Time'] = df['S1_Tsystem'] + df['S2_Tsystem'] + df['S3_Tsystem']
  df['System_Queue_Time'] = df['S1_Tqueue'] + df['S2_Tqueue'] + df['S3_Tqueue']
  df = df.drop(columns=['Material ID']).reset_index(drop=True) # This will drop all columns named 'Material ID'

  return(df)

def simular_planta(tasa_llegadas, servicios, servidores, tiempo):
    """
    Simula una planta de producción de 4 estaciones en tándem con tiempos
    de servicio exponenciales y llegadas de Poisson.

    Parámetros de entrada:
    - tasa_llegadas: Tasa de llegadas al sistema.
    - servicios: Diccionario con los tiempos de servicio para cada estación y el tiempo de transporte entre estaciones
    - servidores: Lista con el número de servidores en cada estación.
    - tiempo: Tiempo de simulación.

    Retorna:
    - DataFrame con los resultados de la simulación:
      * Pieza_ID: ID de la pieza
      * Station: Estación en la que se encuentra la pieza
      * Tin: Tiempo de llegada
      * Tinit_service: Tiempo de inicio de servicio
      * Tout: Tiempo de salida
      * Tsystem: Tiempo en el sistema
      * Tqueue: Tiempo en la cola
      * Nsystem: Número de piezas en el sistema
      * Nqueue: Número de piezas en la cola
    """
    import simpy  
    # Dataframe de resultados de la simulación
    results = []
    # Define the simulation environment
    env = simpy.Environment()

    # Definimos los recursos de cada estación
    resources = {
        'Station_01': simpy.Resource(env, capacity=servidores[0]),
        'Station_02': simpy.Resource(env, capacity=servidores[1]),
        'Station_03': simpy.Resource(env, capacity=servidores[2]),
        'Station_04': simpy.Resource(env, capacity=servidores[3])
    }

    #### B1. Inicialización de tiempos del sistema  #####
    class Material:
        def __init__(self, id_material):
            self.id = id_material
            # Inicializamos diccionario para guardar tiempos de las 4 estaciones
            self.tiempos = {estacion: {'tarr': 0, 'tini': 0, 'tout': 0} for estacion in resources}

    #### B2. Funcionamiento por el sistema  #####
    
    # Función para simular los datos de una estación
    def simular_estacion(env, material, estacion):
        resource = resources[estacion]
        
        # 1. Registro Tiempo de llegada (Tin)
        material.tiempos[estacion]['tarr'] = env.now
        
        with resource.request() as req:
            # Captura de estado del sistema A LA LLEGADA
            nsystem = len(resource.queue) + resource.count
            nqueue = len(resource.queue)
            
            # Solicitud del recurso (espera en cola si es necesario)
            yield req
            
            # 2. Registro Tiempo de inicio de servicio
            material.tiempos[estacion]['tini'] = env.now
            
            # 3. Generación del Tiempo de Servicio (Aleatorio Exponencial)
            # random.expovariate requiere lambda = 1 / media
            media_servicio = servicios[estacion]['servicio_media']
            tiempo_real_servicio = random.expovariate(1.0 / media_servicio)
            
            yield env.timeout(tiempo_real_servicio)
            
        # 4. Registro Tiempo de salida (Tout)
        material.tiempos[estacion]['tout'] = env.now

        # Guardar datos de la estación en la lista de resultados
        results.append([
            material.id, 
            estacion,
            material.tiempos[estacion]['tarr'],
            material.tiempos[estacion]['tini'],
            material.tiempos[estacion]['tout'],
            material.tiempos[estacion]['tout'] - material.tiempos[estacion]['tarr'], # Tsystem
            material.tiempos[estacion]['tini'] - material.tiempos[estacion]['tarr'], # Tqueue
            nsystem, 
            nqueue
        ])

    ## Movimiento por el sistema (Ruta Lineal S1 -> S2 -> S3 -> S4)
    def servicio(env, material):
        # Estación 1
        yield env.process(simular_estacion(env, material, 'Station_01'))
        yield env.timeout(servicios['Station_01']['transporte'])
        
        # Estación 2
        yield env.process(simular_estacion(env, material, 'Station_02'))
        yield env.timeout(servicios['Station_02']['transporte'])
        
        # Estación 3
        yield env.process(simular_estacion(env, material, 'Station_03'))
        yield env.timeout(servicios['Station_03']['transporte'])
        
        # Estación 4
        yield env.process(simular_estacion(env, material, 'Station_04'))
        yield env.timeout(servicios['Station_04']['transporte'])

    #### B3. Proceso de llegadas al sistema (Poisson) #####
    def llegadas(env, simulation_time):
        material_id = 1
        while env.now < simulation_time:
            # Generar siguiente llegada (Exponencial basada en tasa lambda)
            tiempo_entre_llegadas = random.expovariate(tasa_llegadas)
            yield env.timeout(tiempo_entre_llegadas)
            
            material = Material(material_id)
            env.process(servicio(env, material))
            material_id += 1

    ### Ejecución ###
    env.process(llegadas(env, tiempo))
    env.run(until=tiempo)

    # Creación del DataFrame final
    df = pd.DataFrame(results, columns=[
        'Pieza_ID', 'Station',
        'Tin', 'Tinit_service', 'Tout', 
        'Tsystem', 'Tqueue', 'Nsystem', 'Nqueue'
    ])
    
    return df

def simular_planta_serie(tasa_llegadas, datos_produccion, servidores, tiempo):
    """
    Simula una planta de 3 máquinas en serie utilizando un diccionario unificado
    para tiempos de servicio (Normal) y transporte (Fijo).
    """
    import simpy  
    results = []
    env = simpy.Environment()

    # Recursos (Máquinas)
    resources = {
        'Maquina_01': simpy.Resource(env, capacity=servidores[0]),
        'Maquina_02': simpy.Resource(env, capacity=servidores[1]),
        'Maquina_03': simpy.Resource(env, capacity=servidores[2])
    }

    #### B1. Clase Pieza #####
    class Pieza:
        def __init__(self, id_pieza):
            self.id = id_pieza
            self.tiempos = {m: {'tarr': 0, 'tini': 0, 'tout': 0} for m in resources}

    #### B2. Procesamiento en Máquina #####
    def procesar_en_maquina(env, pieza, maquina_nombre):
        resource = resources[maquina_nombre]
        
        # Registro llegada
        pieza.tiempos[maquina_nombre]['tarr'] = env.now
        
        with resource.request() as req:
            nsystem = len(resource.queue) + resource.count
            nqueue = len(resource.queue)
            
            yield req
            
            # Registro inicio servicio
            pieza.tiempos[maquina_nombre]['tini'] = env.now
            
            # --- Lectura de parámetros del diccionario unificado ---
            media = datos_produccion[maquina_nombre]['media']
            desviacion = datos_produccion[maquina_nombre]['std']
            
            # Generación tiempo aleatorio (Normal)
            tiempo_proceso = random.normalvariate(media, desviacion)
            tiempo_proceso = max(0, tiempo_proceso) # Evitar tiempos negativos
            
            yield env.timeout(tiempo_proceso)
            
        # Registro salida
        pieza.tiempos[maquina_nombre]['tout'] = env.now

        results.append([
            pieza.id, maquina_nombre,
            pieza.tiempos[maquina_nombre]['tarr'],
            pieza.tiempos[maquina_nombre]['tini'],
            pieza.tiempos[maquina_nombre]['tout'],
            pieza.tiempos[maquina_nombre]['tout'] - pieza.tiempos[maquina_nombre]['tarr'],
            pieza.tiempos[maquina_nombre]['tini'] - pieza.tiempos[maquina_nombre]['tarr'],
            nsystem, nqueue
        ])

    #### Flujo Lineal (M1 -> Cinta -> M2 -> Cinta -> M3) #####
    def flujo_produccion(env, pieza):
        
        # --- ETAPA 1 ---
        yield env.process(procesar_en_maquina(env, pieza, 'Maquina_01'))
        # Transporte asociado a la salida de M1 (hacia M2)
        yield env.timeout(datos_produccion['Maquina_01']['transporte'])
        
        # --- ETAPA 2 ---
        yield env.process(procesar_en_maquina(env, pieza, 'Maquina_02'))
        # Transporte asociado a la salida de M2 (hacia M3)
        yield env.timeout(datos_produccion['Maquina_02']['transporte'])
        
        # --- ETAPA 3 ---
        yield env.process(procesar_en_maquina(env, pieza, 'Maquina_03'))
        # Transporte asociado a la salida de M3 (Salida sistema = 0)
        yield env.timeout(datos_produccion['Maquina_03']['transporte'])

    #### B3. Generador de Llegadas #####
    def generador_llegadas(env, simulation_time):
        pieza_id = 1
        while env.now < simulation_time:
            yield env.timeout(random.expovariate(tasa_llegadas))
            
            nueva_pieza = Pieza(pieza_id)
            env.process(flujo_produccion(env, nueva_pieza))
            pieza_id += 1

    ### Ejecución ###
    env.process(generador_llegadas(env, tiempo))
    env.run(until=tiempo)

    df = pd.DataFrame(results, columns=[
        'Pieza_ID', 'Maquina',
        'Tin', 'Tinit_service', 'Tout', 
        'Tsystem', 'Tqueue', 'Nsystem', 'Nqueue'
    ])
    
    return df

def simular_planta3(tasa_llegadas, tiempos, prob_rechazo, tiempo):
  """
  Función para simular el comportamiento de la planta de producción 3

  Parámetros de entrada:
  - tasa_llegadas: Tasa de llegadas de piezas al sistema
  - tiempos: Diccionario con los tiempos de servicio y transporte para cada estación
  - tiempo: Tiempo total de simulación

  Devuelve:
  - df: DataFrame con los resultados de la simulación y columnas:
    * Material ID: ID del material
    * Estación: Estación en la que se encuentra el material
    * Tin: Tiempo de llegada a la estación
    * Tinit_service: Tiempo de inicio del servicio en la estación
    * Tout: Tiempo de salida de la estación
    * Tsystem: Tiempo de permanencia en el sistema
    * Tqueue: Tiempo de permanencia en la cola
    * Nsystem: Número de clientes en el sistema
    * Nqueue: Número de clientes en la cola
  """
  
  import simpy  
  # Dataframe de resultados de la simulación
  results = []
  # Define the simulation environment
  env = simpy.Environment()

  # Definimos los recursos de cada estación
  # Asumiendo capacidad infinita para todas las estaciones
  # excepto el horno que procesa lotes de 10
  resources = {
    'Entrada Bodega': simpy.Resource(env, capacity=float('inf')),
    'Cortadora': simpy.Resource(env, capacity=float('inf')),
    'Torno': simpy.Resource(env, capacity=float('inf')),
    'Molino': simpy.Resource(env, capacity=float('inf')),
    'Inspección': simpy.Resource(env, capacity=float('inf')),
    'Horno': simpy.Resource(env, capacity=1),  # Capacidad 1 para procesar lotes
    'Salida Bodega': simpy.Resource(env, capacity=float('inf'))
  }

  #### B1. Inicialización de tiempos del sistema  #####
  #####################################################

  # Clase para la incialización de tiempos en el sistema de cada llegada
  class Material:
    def __init__(self, id):
        self.id = id
        self.tiempos = {estacion: {'tarr': 0, 'tini': 0, 'tout': 0}
                        for estacion in resources}
        self.rechazada = False

  #### B2. Funcionamiento por el sitema  #####
  ############################################

  # Función para simular los datos de una estación
  def simular_estacion(env, material, estacion):
    resource = resources[estacion]
    # Tiempo de llegada a la estación
    material.tiempos[estacion]['tarr'] = env.now
    with resource.request() as req:
        # Número de clientes en el sistema y en la cola
        nsystem = len(resource.queue) + resource.count
        nqueue = len(resource.queue)
        yield req
        # Tiempo de inicio del servicio
        material.tiempos[estacion]['tini'] = env.now
        # Tiempo de servicio
        yield env.timeout(tiempos[estacion]['servicio'])
    # Tiempo de salida de la estación
    material.tiempos[estacion]['tout'] = env.now

    # Guardar datos de la estación
    results.append([material.id, estacion,
                    material.tiempos[estacion]['tarr'],
                    material.tiempos[estacion]['tini'],
                    material.tiempos[estacion]['tout'],
                    material.tiempos[estacion]['tout'] - material.tiempos[estacion]['tarr'],
                    material.tiempos[estacion]['tini'] - material.tiempos[estacion]['tarr'],
                    nsystem, nqueue])

  ## Movimiento por el sistema
  def servicio(env, material):
    # Entrada Bodega
    yield env.process(simular_estacion(env, material, 'Entrada Bodega'))
    # Transporte a Cortadora
    yield env.timeout(tiempos['Entrada Bodega']['transporte'])
    # Cortadora
    yield env.process(simular_estacion(env, material, 'Cortadora'))
    # Transporte a Torno (5 piezas)
    for _ in range(5):
        yield env.timeout(tiempos['Cortadora']['transporte'])
        # Torno
        yield env.process(simular_estacion(env, material, 'Torno'))
        # Transporte a Molino
        yield env.timeout(tiempos['Torno']['transporte'])
        # Molino
        yield env.process(simular_estacion(env, material, 'Molino'))
        # Transporte a Inspección
        yield env.timeout(tiempos['Molino']['transporte'])
        # Inspección
        yield env.process(simular_estacion(env, material, 'Inspección'))
        # Control de calidad
        if random.random() < prob_rechazo:
            material.rechazada = True
            break  # Si es rechazada, se sale del bucle
        else:
            # Transporte a Horno si no es rechazada
            yield env.timeout(tiempos['Inspección']['transporte'])
    # Horno (lote de 10 piezas - se asume que se esperan)
    if not material.rechazada:
        yield env.process(simular_estacion(env, material, 'Horno'))
        # Transporte a Salida Bodega (5 productos terminados)
        for _ in range(5):
            yield env.timeout(tiempos['Horno']['transporte'])
            # Salida Bodega
            yield env.process(simular_estacion(env, material, 'Salida Bodega'))

  #### B3. proceso de llegadas al sistema  #####
  ##############################################

  # Definimos el proceso de llegadas
  def llegadas(env, simulation_time):
    material_id = 1
    while env.now < simulation_time:  # Admit materials until simulation time
        yield env.timeout(random.expovariate(tasa_llegadas))  # arrivals per minute
        material = Material(material_id)
        env.process(servicio(env, material))
        material_id += 1

  ### Simualción y almacenamiento de resultados ###
  #################################################

  # Ejecutamos la simulación
  simulation_time = tiempo
  env.process(llegadas(env, simulation_time))
  env.run(until=simulation_time)

  # Dataframe de resultados
  df = pd.DataFrame(results, columns=['Material ID', 'Estación',
                                    'Tin', 'Tinit_service', 'Tout', 'Tsystem', 'Tqueue', 'Nsystem', 'Nqueue'])
  return df

def simular_control_calidad(tasa_llegadas, tasa_servicio, prob_retorno, servidores, tiempo):
  """
  Simula el comportamiento de un sistema de producción con control de calidad.

  Parámetros:
   - tasa_llegadas (float): Tasa de llegadas de material al sistema.
   - tasa_servicio (list): Lista de tasas de servicio en cada estación.
   - prob_retorno (float): Probabilidad de retorno
   - servidores (list): Lista de números de servidores en cada estación.
    tiempo (int): Tiempo total de simulación en minutos.

  """

  # Dataframe de resultados de la simulación
  results = []
  # Define the simulation environment
  env = simpy.Environment()

  # Definimos los recursos de cada estación
  servers1 = servidores[0]; servers2 = servidores[1]; servers3 = servidores[2]
  station1 = simpy.Resource(env, capacity = servers1)
  station2 = simpy.Resource(env, capacity = servers2)
  station3 = simpy.Resource(env, capacity = servers3)

  #### B1. Inicialización de tiempos del sistema  #####
  #####################################################

  # Clase para la incialización de tiempos en el sistema de cada llegada
  class Sistema:
    def __init__(self, id):
        self.id = id
        self.station1_tarr = 0
        self.station1_tini = 0
        self.station1_tout = 0
        self.station2_tarr = 0
        self.station2_tini = 0
        self.station2_tout = 0
        self.station3_tarr = 0
        self.station3_tini = 0
        self.station3_tout = 0

  #### B2. Funcionamiento por el sitema  #####
  ############################################

  # Función para simular los datos de una estación
  def simular_estacion(env, material, station, tasa_servicio, station_name):
    # Tiempo de llegada a la estación
    setattr(material, f"{station_name}_tarr", env.now)
    with station.request() as req:
        # Número de clientes en el sistema y en la cola
        nsystem = len(station.queue) + station.count
        nqueue = len(station.queue)
        yield req
        # Tiempo de inicio del servicio
        setattr(material, f"{station_name}_tini", env.now)
        # Tiempo de servicio
        yield env.timeout(random.expovariate(tasa_servicio))
    # Tiempo de salida de la estación
    setattr(material, f"{station_name}_tout", env.now)
    # Guardar datos de la estación
    return [material.id,
            getattr(material, f"{station_name}_tarr"),
            getattr(material, f"{station_name}_tini"),
            getattr(material, f"{station_name}_tout"),
            getattr(material, f"{station_name}_tout") - getattr(material, f"{station_name}_tarr"),
            getattr(material, f"{station_name}_tini") - getattr(material, f"{station_name}_tarr"),
            nsystem, nqueue]

  ## Movimiento por el sistema
  def servicio(env, material):
    # Estación 1
    station1_data = yield env.process(simular_estacion(env, material, station1, tasa_servicio[0], "station1")) # Get station1 data
    # Estación 2
    station2_data = yield env.process(simular_estacion(env, material, station2, tasa_servicio[1], "station2")) # Get station2 data
    # Estacion 3
    station3_data = yield env.process(simular_estacion(env, material, station3, tasa_servicio[2], "station3")) # Get station3 data

    # Posible retorno a la estación 1
    retorno = 0
    if random.random() < prob_retorno:
        env.process(servicio(env, material))  # Return to station 1
        retorno = 1  # Si retorna, cambiamos el valor a 1

    # unimos los resultados de las estaciones
    results.append(station1_data + station2_data + station3_data+ [retorno])

  #### B3. proceso de llegadas al sistema  #####
  ##############################################

  # Definimos el proceso de llegadas
  def llegadas(env, simulation_time):
    material_id = 1
    while env.now < simulation_time:  # Admit materials until simulation time
        yield env.timeout(random.expovariate(tasa_llegadas))  # arrivals per minute
        material = Sistema(material_id)
        env.process(servicio(env, material))
        material_id += 1

  ### Simualción y almacenamiento de resultados ###
  #################################################

  # Ejecutamos la simulación
  simulation_time = tiempo  # Define simulation time
  env.process(llegadas(env, simulation_time))  # Pass simulation time to material_arrival
  env.run(until=simulation_time)  # Simulate for the defined time

  # Dataframe de resultados
  df = pd.DataFrame(results, columns=['Material ID',
                                    'S1_Tin', 'S1_Tinit_service', 'S1_Tout', 'S1_Tsystem', 'S1_Tqueue', 'S1_Nsystem', 'S1_Nqueue',
                                    'Material ID', 'S2_Tin', 'S2_Tinit_service', 'S2_Tout', 'S2_Tsystem', 'S2_Tqueue', 'S2_Nsystem', 'S2_Nqueue',
                                    'Material ID', 'S3_Tin', 'S3_Tinit_service', 'S3_Tout', 'S3_Tsystem', 'S3_Tqueue', 'S3_Nsystem', 'S3_Nqueue',
                                    'Retorno'])
  df = df.sort_values(by=['S1_Tin'])

  # Tiempos totales en el sistema y en al cola
  df['System_Time'] = df['S1_Tsystem'] + df['S2_Tsystem'] + df['S3_Tsystem']
  df['System_Queue_Time'] = df['S1_Tqueue'] + df['S2_Tqueue'] + df['S3_Tqueue']
  df = df.drop(columns=['Material ID']).reset_index(drop=True) # This will drop all columns named 'Material ID'

  return df


